version: "3.9"

services:
  telegram-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: telegram-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
